# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RongCloudDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!


platform :ios, '9.0'
pod 'SDWebImage', '~> 4.0'
#pod 'RongCloudIM/IMLib', '~> 5.1.2.1'
#pod 'RongCloudIM/IMKit', '5.1.2.1'
#pod 'RongCloudIM/IMKit', '~> 5.1.2.1'

pod 'RongCloudOpenSource/IMKit','~>5.1.2'           # IMKit

  # Pods for RongCloudDemo

  target 'RongCloudDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RongCloudDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
